name: to_do
description: "To-Do Flutter App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.1        # latest stable version :contentReference[oaicite:0]{index=0}
  go_router: ^16.2.4         # already latest :contentReference[oaicite:1]{index=1}
  smooth_page_indicator: ^1.2.1  # still latest :contentReference[oaicite:2]{index=2}
  google_fonts: ^6.3.2        # latest version :contentReference[oaicite:3]{index=3}
  flutter_bloc: ^9.1.1        # latest version :contentReference[oaicite:4]{index=4}
  local_auth: ^3.0.0
  cupertino_icons: ^1.0.8
  local_auth_android: ^2.0.0
  local_auth_ios: ^1.1.5
  firebase_core: ^4.2.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/